# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Template Variables (users replace these)
state_name: "alladdin1983"  # e.g., "Kansas"
state_abbrev: "ALLADDIN"  # e.g., "KS"
state_url_subdomain: "alladdin1983"  # e.g., "kansas"

# Derived Configuration (auto-generated from variables)
title: "Alladdin1983"
description: "alladdin1983 State DOGE Network site for government transparency and efficiency."
url: "https://alladdin1983.dogenetwork.org/"

version: "0.3.0"
template: "DOGE Network Ruby"
template_repo: "https://github.com/DOGE-network/DOGE_Network_Ruby_Template"
last_updated: "2025-10-06"
email: community@dogenetwork.org
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: alladdin1983 # replace with your state's twitter username
github_username: alladdin1983 # replace with your github username
logo_doge: "/doge-network.png"
logo_state: "/state-flag.jpeg" # replace with your state's flag

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Footer links
footer_links:
  - title: About
    url: https://dogenetwork.org/about
  - title: Documentation
    url: https://dogenetwork.org/docs
  - title: Meetings
    url: https://dogenetwork.org/meetings
  - title: Schedule
    url: https://dogenetwork.org/schedule
  - title: Calendar
    url: https://dogenetwork.org/calendar
  - title: GitHub
    url: https://github.com/doge-network

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
